/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmadoRouteImport } from './routes/confirmado'
import { Route as ChegadaRouteImport } from './routes/chegada'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ConfirmadoRoute = ConfirmadoRouteImport.update({
  id: '/confirmado',
  path: '/confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const ChegadaRoute = ChegadaRouteImport.update({
  id: '/chegada',
  path: '/chegada',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/chegada': typeof ChegadaRoute
  '/confirmado': typeof ConfirmadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/chegada': typeof ChegadaRoute
  '/confirmado': typeof ConfirmadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/chegada': typeof ChegadaRoute
  '/confirmado': typeof ConfirmadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/cadastro' | '/chegada' | '/confirmado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/cadastro' | '/chegada' | '/confirmado'
  id: '__root__' | '/' | '/admin' | '/cadastro' | '/chegada' | '/confirmado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  ChegadaRoute: typeof ChegadaRoute
  ConfirmadoRoute: typeof ConfirmadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmado': {
      id: '/confirmado'
      path: '/confirmado'
      fullPath: '/confirmado'
      preLoaderRoute: typeof ConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chegada': {
      id: '/chegada'
      path: '/chegada'
      fullPath: '/chegada'
      preLoaderRoute: typeof ChegadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  ChegadaRoute: ChegadaRoute,
  ConfirmadoRoute: ConfirmadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
